name: CI

on:
  push:
    branches:
      - github_actions

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g nativescript@rc
    - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py --user
    - run: pip install six --user
    - uses: actions/checkout@v1
    - run: tns create appTest --template tns-template-hello-world@rc
    - run: ls -la
    - run: cd appTest
    - run: ls -la
    - run: npm i nativescript-dev-webpack@rc --save-dev
    - run: npm install
    - run: ls -la
    - run: tns --version
    - run: tns run ios --justlaunch
    - run: sed -ie 's$taps$clicks$g' app/main-view-model.js